BEGIN;
INSERT INTO tf_category(name,description,image_url) VALUES ('General Cleaning','clean your house','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Moving Help','pack your stuff','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('General Handyman','hang your shelves','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Light Delivery','Get small packages delivered to your feet','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Basic Furniture Assembly','IKEA and similar basic projects','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Deep Cleaning','Let a tasker clean specific areas in your house','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Sewing','Let a tasker sew your clothes','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Yard Work and Removal','Let a tasker bring order to your garden by mowing the lawn or cutting trees','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Shopping','Shopping for you and your demands','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Advanced Furniture Assembly','More difficult assembly involving tool work','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Decoration','Decoration work for your house or your garden','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Laundry and Ironing','Make sure your clothes get laundered and ironed','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Pet Sitting','Let a trustable tasker take care of your pet','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Cooking and Baking','Enjoy food and desserts made by our taskers on your order','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Photography','Let a professional tasker take photos for you during a trip','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Window Cleaning','Make sure your windows get cleaned','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Heavy Delivery','Get big packages delivered to your house or any other chosen place','/image/img001.jpg');
INSERT INTO tf_category(name,description,image_url) VALUES ('Running errands','Let a tasker run your small errands between locations','/image/img001.jpg');
COMMIT;

BEGIN;
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Tom Lee','tom@gmail.com','tomlee','123456','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Sam Tahard','sam23@gmail.com','samboi','ihavedogs','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('John Johnson','john@gmail.com','john123','ilovecats','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Sally Micheala','sally@gmail.com','sakija','rosesnguns','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Sammy Curtis','sammy3@hotmail.com','rambo','456123','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Johnny Bravo','john@hotmail.com','john1234','dearjohn','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Sally Riviera','sal.rivi@hotmail.com','harryman','123456','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Henry Lee Johnson','henryLee@gmail.com','hLee','1112131415','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Kong Wee Chan','kongwee22@hotmail.com','KWee22','bestpassever','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Ruhat Abdulla','gohhuatla@hotmail.com','huatla','huatla1','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Michael Davidson','helpFOOLer@gmail.com','helpFOOL','fooler','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('tf_stephane Bressane','admin123@gmail.com','admin','246810','/image/img001.jpg',true);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Kim Jong Un','pokemonGO@hotmail.com','pikachu','1357911','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Abdullay Ahmeti','useFOOL@gmail.com','helpme2','1123581321','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('John Adam','finaltf_user@gmail.com','finalize','passerword','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Tommy Hilfiger','tomlee.soccer@gmail.com','tomleee','mycat123','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Ilhan Mansiz','taskhunter@hotmail.com','taskhunter','greedisgood','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Jacob Thorell','mrtasker@gmail.com','mrtasker','iwillhelp','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Axel Ingrosso','especiale@gmail.com','specialone','bambam','/image/img001.jpg',false);
INSERT INTO tf_user(name,email,uname,password,image_url,admin) VALUES ('Mike Bierbier','voldemort@gmail.com','voldemort','tibiaisgood','/image/img001.jpg',false);
COMMIT;

BEGIN;
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,1,true,1,4,'02-03-2016 17:00:00','02-03-2016 18:00:00','Market delivery','things needed to carry to my home',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (true,1,true,1,9,'03-03-2016 17:00:00','03-03-2016 20:00:00','Shopping partner','I need someone to go to a mall with me', NULL, NULL);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,1,false,7,9,'03-03-2016 17:00:00','04-03-2016 17:00:00','Buying a pair of shoes','I need accompany to go to a mall',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (true,2,true,11,5,'03-03-2016 17:00:00','04-03-2016 17:00:00','Hanging shelves','I need assistance', NULL, NULL);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (true,1,true,4,2,'03-03-2016 17:00:00','04-03-2016 17:00:00','Moving my house','I need help to carry my stuff', NULL, NULL);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (true,1,true,14,2,'03-03-2016 17:00:00','04-03-2016 17:00:00','Moving my office','Need 1 person to carry my stuff', NULL, NULL);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (true,2,false,3,5,'03-03-2016 17:00:00','04-03-2016 17:00:00','IKEA wardrobe assembly','I bought huge wardrobe, two people needed', NULL, NULL);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (true,3,true,9,15,'03-03-2016 17:00:00','04-03-2016 17:00:00','Do my photography','Need three people to take my photos at different places', NULL, NULL);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,1,false,12,14,'03-03-2016 17:00:00','04-03-2016 17:00:00','Make me soup','I need someone to cook me basic soups',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,4,true,10,13,'03-03-2016 17:00:00','04-03-2016 17:00:00','Take care of my dogs','I need 4 people to take care of my 8 dogs because',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (true,1,false,5,11,'03-03-2016 17:00:00','04-03-2016 17:00:00','Decorate my house','I need someone to decorate my house ceiling before my birthday party', NULL, NULL);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (true,2,true,16,6,'03-03-2016 17:00:00','04-03-2016 17:00:00','I need deep cleaning for my three toilets','I need two people to clean my toilets at home', NULL, NULL);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (true,1,true,14,16,'03-03-2016 17:00:00','04-03-2016 17:00:00','Clean my windows','I need someone to clean all the windows at my place', NULL, NULL);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,1,true,5,4,'03-03-2016 17:00:00','04-03-2016 17:00:00','Walmart delivery','I have some stuff left at Walmart and I need someone to carry them home for me',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,1,false,15,4,'03-03-2016 17:00:00','04-03-2016 17:00:00','Deliver my special-order cake','I am preparing for my sons birthday and I need someone to get me his cake from the bakery',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,2,false,12,8,'03-03-2016 17:00:00','04-03-2016 17:00:00','Mow my 1ha lawn','I need two people to mow my rather big lawn',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,1,false,8,12,'03-03-2016 17:00:00','04-03-2016 17:00:00','Iron my suits','I need to have 4 suits ironed before my meeting tomorrow',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,1,false,7,13,'03-03-2016 17:00:00','04-03-2016 17:00:00','Take care of my two cats','I am looking for a cat lover like to me take care of my cats',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,2,false,10,17,'03-03-2016 17:00:00','04-03-2016 17:00:00','Deliver my sofas','I need two strong guys to deliver my sofas to an old friend',1.265,102.58417);
INSERT INTO tf_task(step,npeople,completed,creator,cid,start_time,end_time,title,description,latitude,longitude) VALUES (false,1,false,2,18,'03-03-2016 17:00:00','04-03-2016 17:00:00','Run my errands','I am looking for a fast-traveling teenager who is able to submit some documents for me',1.265,102.58417);
COMMIT;

BEGIN;
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (1,2,8,true,'I am really glad and impressed by the service!');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (1,12,0,false,null);
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (4,4,5,true,'I hoped for better service.');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (5,3,9,true,'Really good job, thank you so much!');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (5,4,0,false,null);
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (6,2,2,true,'I am truly dissapointed and I can not find my cat again');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (7,5,0,false,null);
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (3,3,3,true,'I will never trust you again!');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (3,4,0,false,null);
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (8,8,0,false,null);
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (9,7,0,true,'Really poor service');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (10,18,9,true,'I loved the level of service and I will tell others about your service');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (11,17,0,false,null);
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (12,15,5,true,'The service was poor but the volunteer was cute so it is okey');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (13,14,2,true,'Very bad communication skills here I feel');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (14,11,9,true,'I love this site, everyone is so nice');
INSERT INTO tf_pick(tid,uid,score,accepted,comment) VALUES (12,14,5,true,'The service was poor and this volunteer was not cute either');
COMMIT;

BEGIN;
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (1,4,1.11,102.2467,'Get tools for the job',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (2,4,1.265,102.58417,'Hang the shelves',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (1,2,1.2265,93.858417,'Find shopping centre', true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (2,2,1.65,93.58417,'Buy suitable clothes',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (1,5,1.2,102.858417,'Find moving car',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (2,5,1.11,102.58417,'Carry stuff from my house out',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (1,6,1.4265,100.858417,'Find moving car',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (2,6,1.232,102.17,'Take out stuff from my office',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (1,7,1.28265,102.858417,'Hold the instructions visible',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (2,7,1.342711,103.732467,'Put the pieces together',false);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (1,8,1.28265,103.858417,'Take pictures of me around Marina Bay Sands',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (2,8,1.2826,103.85417,'Take pictures of me around Gardens by the bay',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (1,11,1.2711,103.932467,'Find appropriate decorations',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (2,11,1.211,103.67,'Hang up the decorations',false);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (1,12,1.711,103.32467,'Clean my first toilet',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (2,12,1.711,103.32467,'Clean my second toilet',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (3,12,1.711,103.32467,'Clean my third toilet',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (1,13,1.701,104.1,'Prepare cleaning materials',true);
INSERT INTO tf_step(sid,tid,latitude,longitude,description,completed) VALUES (2,13,1.701,104.1,'Clean the windows',true);
COMMIT;

BEGIN;
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (1,'03-03-2016 17:00:00',2,1,'pick','samboi','tomleee','Market delivery');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (1,'03-03-2016 17:00:00',1,2,'rate','tomleee','samboi','Market delivery');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (3,'03-03-2016 17:00:00',4,7,'pick','sakija','harryman','Buying a pair of shoes');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (3,'03-03-2016 17:00:00',7,4,'rate','harryman','sakija','Buying a pair of shoes');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (4,'03-03-2016 17:00:00',4,11,'pick','sakija','helpFOOL','Hanging shelves');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (4,'03-03-2016 17:00:00',11,4,'rate','helpFOOL','sakija','Hanging shelves');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (5,'03-03-2016 17:00:00',3,4,'pick','john123','sakija','Moving my house');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (5,'03-03-2016 17:00:00',4,3,'rate','sakija','john123','Moving my house');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (6,'03-03-2016 17:00:00',2,14,'pick','samboi','helpme2','Moving my office');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (6,'03-03-2016 17:00:00',14,2,'rate','helpme2','samboi','Moving my office');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (8,'03-03-2016 17:00:00',8,9,'pick','hLee','KWee22','Do my photography');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (7,'03-03-2016 17:00:00',5,3,'pick','rambo','john123','IKEA wardrobe assembly');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (10,'03-03-2016 17:00:00',18,10,'pick','mrtasker','huatla','Take care of my dogs');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (10,'03-03-2016 17:00:00',10,18,'rate','huatla','mrtasker','Take care of my dogs');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (12,'03-03-2016 17:00:00',15,16,'pick','finalize','tomlee','I need deep cleaning for my three toilets');
INSERT INTO tf_history(tid,time,u1id,u2id,type,u1name,u2name,ttitle) VALUES (12,'03-03-2016 17:00:00',16,15,'rate','tomlee','finalize','I need deep cleaning for my three toilets');
COMMIT;