version: '2'
services:
  app:
    build: app
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./app:/app
      - /app/node_modules
  api:
    build: api
    depends_on:
      - db
    volumes:
      - ./api:/var/www/api
      - /var/www/api/vendor
  db:
    image: wnameless/postgresql-phppgadmin
    ports:
      - '6000:5432'
      - '7000:80'
    env_file:
      - development.env
    volumes:
      - /var/lib/postgresql/data